import turtle
import time

from turtle import *
wn=turtle.Screen()
wn.bgcolor("black")
wn.title('Turtle')
pp=turtle.Turtle()
pp.pensize(5)
pp.penup()
pp.goto(0,200)
pp.pendown()
pp.pencolor('deeppink')
pp.right(60)
for i in range(4):
    if i==3:
        pp.penup()
        pp.setpos(-45,170)
        pp.pendown()
        pp.pencolor("white")
        pp.circle(50)
        pp.pencolor('deeppink')
        pp.penup()
        pp.setpos(0,200)
        pp.pendown()
    pp.forward(170)
    pp.right(120)
pp.pencolor('black')
pp.right(270)
pp.forward(20)
pp.pencolor('deeppink')
for i in range(4):
    if i==1:
        pp.forward(84)
        pp.color("white")
        pp.penup()
        pp.setpos(0, -85)
        pp.pendown()
        pp.circle(50)
        pp.color("deeppink")
        pp.penup()
        pp.setpos(0, -135)
        pp.pendown()
        pp.forward(84)
        pp.right(90)
    else:
        pp.forward(168)
        pp.right(90)

pp.fillcolor("goldenrod")
pp.pencolor('darkgoldenrod')
#1
pp.begin_fill()
pp.circle(43)
pp.end_fill()
pp.right(250)
pp.begin_fill()
for i in range(5):
    pp.pencolor('darkgoldenrod')
    pp.forward(80)
    pp.right(145)
pp.end_fill()
pp.right(170)
pp.pencolor('slategrey')
pp.forward(5)

#2
pp.pencolor('darkgoldenrod')
pp.right(60)
pp.begin_fill()
pp.circle(50)
pp.end_fill()
pp.right(270)
for i in range(4):
  pp.begin_fill()
  pp.forward(50)
  pp.right(120)
pp.end_fill()
for i in range(6):
  pp.begin_fill()
  pp.right(90)
  pp.forward(40)
  pp.end_fill()
#3

pp.penup()
pp.setpos(180,-90)
pp.pendown()
pp.right(-150)
pp.pencolor('darkgoldenrod')
pp.begin_fill()
pp.circle(50,180)
pp.left(90)
pp.forward(35)
pp.right(90)
pp.forward(30)
pp.left(180)
pp.circle(10,-180)
pp.left(180)
pp.circle(5,-180)
pp.circle(25,180)
pp.forward(30)
pp.right(88)
pp.forward(48)
pp.left(95)
pp.circle(60)
pp.end_fill()
pp.backward(10)
pp.right(110)
turtle.done()
